apiVersion: v1
kind: Service
metadata:
  name: FirstNexus
  labels:
    app: FirstNexus
spec:
  type: ClusterIP
  selector:
    app: FirstNexus
  ports:
    - name: gateway
      port: 18789
      targetPort: 18789
      protocol: TCP
