export const browserCoreExamples = [
  "nexusclaw browser status",
  "nexusclaw browser start",
  "nexusclaw browser stop",
  "nexusclaw browser tabs",
  "nexusclaw browser open https://example.com",
  "nexusclaw browser focus abcd1234",
  "nexusclaw browser close abcd1234",
  "nexusclaw browser screenshot",
  "nexusclaw browser screenshot --full-page",
  "nexusclaw browser screenshot --ref 12",
  "nexusclaw browser snapshot",
  "nexusclaw browser snapshot --format aria --limit 200",
  "nexusclaw browser snapshot --efficient",
  "nexusclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "nexusclaw browser navigate https://example.com",
  "nexusclaw browser resize 1280 720",
  "nexusclaw browser click 12 --double",
  'nexusclaw browser type 23 "hello" --submit',
  "nexusclaw browser press Enter",
  "nexusclaw browser hover 44",
  "nexusclaw browser drag 10 11",
  "nexusclaw browser select 9 OptionA OptionB",
  "nexusclaw browser upload /tmp/nexusclaw/uploads/file.pdf",
  'nexusclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "nexusclaw browser dialog --accept",
  'nexusclaw browser wait --text "Done"',
  "nexusclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "nexusclaw browser console --level error",
  "nexusclaw browser pdf",
];
