export const browserCoreExamples = [
  "FirstNexus browser status",
  "FirstNexus browser start",
  "FirstNexus browser start --headless",
  "FirstNexus browser stop",
  "FirstNexus browser tabs",
  "FirstNexus browser open https://example.com",
  "FirstNexus browser focus abcd1234",
  "FirstNexus browser close abcd1234",
  "FirstNexus browser screenshot",
  "FirstNexus browser screenshot --full-page",
  "FirstNexus browser screenshot --ref 12",
  "FirstNexus browser snapshot",
  "FirstNexus browser snapshot --format aria --limit 200",
  "FirstNexus browser snapshot --efficient",
  "FirstNexus browser snapshot --labels",
];

export const browserActionExamples = [
  "FirstNexus browser navigate https://example.com",
  "FirstNexus browser resize 1280 720",
  "FirstNexus browser click 12 --double",
  "FirstNexus browser click-coords 120 340",
  'FirstNexus browser type 23 "hello" --submit',
  "FirstNexus browser press Enter",
  "FirstNexus browser hover 44",
  "FirstNexus browser drag 10 11",
  "FirstNexus browser select 9 OptionA OptionB",
  "FirstNexus browser upload /tmp/FirstNexus/uploads/file.pdf",
  'FirstNexus browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "FirstNexus browser dialog --accept",
  'FirstNexus browser wait --text "Done"',
  "FirstNexus browser evaluate --fn '(el) => el.textContent' --ref 7",
  "FirstNexus browser console --level error",
  "FirstNexus browser pdf",
];
